import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Pill, Calendar, ArrowRight, Search, Download, Plus } from 'lucide-react';
import { DashboardLayout, PageHeader } from '@/components/DashboardLayout';
import { Card, CardHeader } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { useDoctor } from '@/contexts/DoctorContext';
import { demoPatients } from '@/data/demoData';

export function DoctorPrescriptions() {
  const { scannedPatientIds } = useDoctor();
  const [searchQuery, setSearchQuery] = useState('');

  const scannedPatients = demoPatients.filter((p) => scannedPatientIds.includes(p.id));

  const allPrescriptions = scannedPatients.flatMap((p) =>
    p.prescriptions.map((pr) => ({
      ...pr,
      patientName: p.name,
      healthId: p.healthId,
      patientId: p.id,
    }))
  ).sort((a, b) => b.issuedDate.localeCompare(a.issuedDate));

  const filtered = allPrescriptions.filter((pr) => {
    const q = searchQuery.toLowerCase();
    return pr.patientName.toLowerCase().includes(q) || pr.diagnosis.toLowerCase().includes(q) || pr.healthId.toLowerCase().includes(q);
  });

  const handleDownload = (pr: typeof allPrescriptions[0], patientName: string) => {
    const lines = [
      '╔══════════════════════════════════════════╗',
      '║          AROGYA SAFAR — PRESCRIPTION     ║',
      '╚══════════════════════════════════════════╝',
      '',
      `Patient:   ${patientName}`,
      `Health ID: ${pr.healthId}`,
      `Doctor:    ${pr.doctor}`,
      `Date:      ${pr.issuedDate}`,
      `Diagnosis: ${pr.diagnosis}`,
      '',
      '── Medications ──────────────────────────',
      ...pr.medications.map((m) =>
        `• ${m.name} ${m.dosage} — ${m.frequency}, ${m.duration}${m.instructions ? ` (${m.instructions})` : ''}`
      ),
      '',
      `─ Instructions: ${pr.instructions || 'None'}`,
      `─ Refills: ${pr.refills}`,
      `─ Status: ${pr.status}`,
      '',
      '═══════════════════════════════════════════',
      'Generated by Arogya Safar — For demonstration purposes only.',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prescription-${pr.healthId}-${pr.issuedDate}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <DashboardLayout role="doctor">
      <PageHeader
        title="Prescriptions"
        subtitle={`${allPrescriptions.length} prescription(s) across scanned patients`}
        action={
          <Link to="/doctor/scan">
            <Button size="sm" icon={<Plus className="h-4 w-4" />}>New Prescription</Button>
          </Link>
        }
      />

      <Card padding="sm" className="mb-4">
        <div className="flex items-center gap-2">
          <Search className="h-4 w-4 text-ink-400" />
          <input
            type="text"
            placeholder="Search by patient name, diagnosis, or health ID…"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="flex-1 bg-transparent text-sm text-ink-900 placeholder:text-ink-400 focus:outline-none"
          />
        </div>
      </Card>

      {allPrescriptions.length === 0 ? (
        <Card padding="lg" className="text-center">
          <div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-ink-100 mb-3">
            <Pill className="h-7 w-7 text-ink-400" />
          </div>
          <p className="text-ink-900 font-bold">No prescriptions yet</p>
          <p className="text-sm text-ink-500 mt-1">Scan a patient and create a prescription to see it here.</p>
          <Link to="/doctor/scan">
            <Button className="mt-4">Scan Patient</Button>
          </Link>
        </Card>
      ) : (
        <div className="space-y-3">
          {filtered.map((pr, i) => (
            <Card key={i} padding="md">
              <div className="flex items-start justify-between">
                <div className="flex items-start gap-3">
                  <div className="flex h-10 w-10 items-center justify-center rounded-full bg-success-100 text-sm font-bold text-success-700 shrink-0">
                    {pr.patientName.split(' ').map((n: string) => n[0]).join('')}
                  </div>
                  <div>
                    <p className="text-sm font-bold text-ink-900">{pr.patientName}</p>
                    <p className="text-xs text-ink-500">{pr.healthId}</p>
                    <p className="text-sm text-ink-700 mt-1">{pr.diagnosis}</p>
                    <div className="mt-2 space-y-1">
                      {pr.medications.map((m) => (
                        <div key={m.id} className="flex items-center gap-2 text-xs">
                          <Badge tone="info" className="text-[10px] shrink-0">{m.name}</Badge>
                          <span className="text-ink-600">{m.dosage} · {m.frequency} · {m.duration}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
                <div className="text-right shrink-0">
                  <p className="text-xs text-ink-500 flex items-center gap-1 justify-end"><Calendar className="h-3 w-3" />{pr.issuedDate}</p>
                  <Badge tone={pr.status === 'active' ? 'success' : pr.status === 'completed' ? 'info' : 'warning'} className="mt-1">{pr.status}</Badge>
                  <div className="mt-2">
                    <Button size="sm" variant="ghost" onClick={() => handleDownload(pr, pr.patientName)} icon={<Download className="h-3 w-3" />}>
                      Download
                    </Button>
                  </div>
                </div>
              </div>
            </Card>
          ))}
          {filtered.length === 0 && allPrescriptions.length > 0 && (
            <Card padding="md" className="text-center">
              <p className="text-sm text-ink-500">No prescriptions match "{searchQuery}".</p>
            </Card>
          )}
        </div>
      )}
    </DashboardLayout>
  );
}
