import { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import {
  ArrowLeft, User, Download, Plus, Pill, TestTube,
  AlertTriangle, Stethoscope,
} from 'lucide-react';
import { DashboardLayout, PageHeader } from '@/components/DashboardLayout';
import { Card, CardHeader } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge, StatusBadge } from '@/components/ui/Badge';
import { Tabs } from '@/components/ui/Tabs';
import { AddConsultationForm } from '@/components/AddConsultationForm';
import { useDoctor } from '@/contexts/DoctorContext';
import { demoPatients } from '@/data/demoData';
import type { Consultation, Prescription } from '@/types';
import type { TabItem } from '@/components/ui/Tabs';

const tabs: TabItem[] = [
  { id: 'overview', label: 'Overview', icon: <User className="h-4 w-4" /> },
  { id: 'consultations', label: 'Consultations', icon: <Stethoscope className="h-4 w-4" /> },
  { id: 'prescriptions', label: 'Prescriptions', icon: <Pill className="h-4 w-4" /> },
  { id: 'lab', label: 'Lab Reports', icon: <TestTube className="h-4 w-4" /> },
  { id: 'allergies', label: 'Allergies', icon: <AlertTriangle className="h-4 w-4" /> },
];

export function PatientViewPage() {
  const { healthId } = useParams();
  const { addConsultation: ctxAddConsultation, addActivity } = useDoctor();
  const [activeTab, setActiveTab] = useState('overview');
  const [showAddConsultation, setShowAddConsultation] = useState(false);

  const patient = demoPatients.find((p) => p.healthId === healthId);
  if (!patient) {
    return (
      <DashboardLayout role="doctor">
        <PageHeader title="Patient Not Found" />
        <Card padding="lg" className="text-center">
          <p className="text-ink-600">No patient found with Health ID "{healthId}".</p>
          <Link to="/doctor/patients"><Button className="mt-4">Back to Patients</Button></Link>
        </Card>
      </DashboardLayout>
    );
  }

  const handleAddConsultation = (data: Omit<Consultation, 'id'>) => {
    const newConsultation: Consultation = { ...data, id: `c-${Date.now()}` };
    ctxAddConsultation(patient.id, newConsultation);
    addActivity({
      type: 'consultation',
      description: `Added consultation for ${patient.name}: ${data.diagnosis}`,
      patientId: patient.id,
      patientName: patient.name,
    });
    setShowAddConsultation(false);
  };

  const handleDownloadPrescription = (pr: Prescription) => {
    const lines = [
      '╔══════════════════════════════════════════╗',
      '║          AROGYA SAFAR — PRESCRIPTION     ║',
      '╚══════════════════════════════════════════╝',
      '',
      `Patient:   ${patient.name}`,
      `Health ID: ${patient.healthId}`,
      `Doctor:    ${pr.doctor}`,
      `Date:      ${pr.issuedDate}`,
      `Diagnosis: ${pr.diagnosis}`,
      '',
      '── Medications ──────────────────────────',
      ...pr.medications.map((m) =>
        `• ${m.name} ${m.dosage} — ${m.frequency}, ${m.duration}${m.instructions ? ` (${m.instructions})` : ''}`
      ),
      '',
      `─ Instructions: ${pr.instructions || 'None'}`,
      `─ Refills: ${pr.refills}`,
      `─ Status: ${pr.status}`,
      '',
      '═══════════════════════════════════════════',
      'Generated by Arogya Safar — For demonstration purposes only.',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `prescription-${patient.healthId}-${pr.issuedDate}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <DashboardLayout role="doctor">
      <PageHeader
        title={patient.name}
        subtitle={patient.healthId}
        action={
          <Link to="/doctor/patients" className="flex items-center gap-1 text-sm text-primary-600 hover:text-primary-700">
            <ArrowLeft className="h-4 w-4" /> Back to Patients
          </Link>
        }
      />

      {/* Patient header */}
      <Card padding="lg" className="mb-6">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="flex h-16 w-16 items-center justify-center rounded-full bg-primary-100 text-xl font-bold text-primary-700">
              {patient.name.split(' ').map((n) => n[0]).join('')}
            </div>
            <div>
              <h2 className="text-xl font-extrabold text-ink-900">{patient.name}</h2>
              <p className="text-sm text-ink-500">{patient.healthId} · {patient.gender === 'M' ? 'Male' : 'Female'}, {patient.age} years</p>
              <div className="mt-1.5 flex flex-wrap gap-1.5">
                {patient.allergies.length > 0 && patient.allergies.map((a) => <Badge key={a.id} tone="danger">{a.substance}</Badge>)}
                {patient.chronicConditions.length > 0 && patient.chronicConditions.map((c) => <Badge key={c.id} tone="warning">{c.condition}</Badge>)}
              </div>
            </div>
          </div>
          <div className="flex gap-2">
            <Button size="sm" onClick={() => setShowAddConsultation(true)} icon={<Plus className="h-4 w-4" />}>Add Consultation</Button>
            <StatusBadge status={patient.healthStatus === 'stable' ? 'active' : patient.healthStatus === 'critical' ? 'critical' : 'warning'} />
          </div>
        </div>
      </Card>

      {/* Add consultation form */}
      {showAddConsultation && (
        <Card padding="lg" className="mb-6 border-primary-200 bg-primary-50/50">
          <CardHeader title="New Consultation" icon={<Stethoscope className="h-5 w-5" />} action={<Button variant="ghost" size="sm" onClick={() => setShowAddConsultation(false)}>Cancel</Button>} />
          <AddConsultationForm onSubmit={handleAddConsultation} onCancel={() => setShowAddConsultation(false)} />
        </Card>
      )}

      {/* Tabs */}
      <Tabs tabs={tabs} value={activeTab} onChange={setActiveTab} />
      <div className="pt-6">
        {/* Overview */}
        {activeTab === 'overview' && (
          <div className="grid gap-6 lg:grid-cols-3">
            <Card padding="md" className="lg:col-span-2">
              <CardHeader title="Personal Information" icon={<User className="h-5 w-5" />} />
              <div className="grid gap-4 sm:grid-cols-2 text-sm">
                <div><p className="text-xs font-bold uppercase tracking-wider text-ink-400">Full Name</p><p className="text-ink-900">{patient.name}</p></div>
                <div><p className="text-xs font-bold uppercase tracking-wider text-ink-400">Date of Birth</p><p className="text-ink-900">{patient.dateOfBirth}</p></div>
                <div><p className="text-xs font-bold uppercase tracking-wider text-ink-400">Phone</p><p className="text-ink-900">{patient.phone}</p></div>
                <div><p className="text-xs font-bold uppercase tracking-wider text-ink-400">Blood Type</p><p className="text-ink-900">{patient.bloodType}</p></div>
                <div className="sm:col-span-2"><p className="text-xs font-bold uppercase tracking-wider text-ink-400">Address</p><p className="text-ink-900">{patient.address}</p></div>
                <div><p className="text-xs font-bold uppercase tracking-wider text-ink-400">Current District</p><p className="text-ink-900">{patient.currentDistrict}</p></div>
                <div><p className="text-xs font-bold uppercase tracking-wider text-ink-400">Home District</p><p className="text-ink-900">{patient.homeDistrict}</p></div>
              </div>
            </Card>
            <div className="space-y-4">
              <Card padding="md">
                <p className="text-xs font-bold uppercase tracking-wider text-ink-400 mb-2">Emergency Contact</p>
                <p className="text-sm font-semibold text-ink-900">{patient.emergencyContact.name}</p>
                <p className="text-xs text-ink-500">{patient.emergencyContact.relationship} · {patient.emergencyContact.phone}</p>
              </Card>
              <Card padding="md">
                <p className="text-xs font-bold uppercase tracking-wider text-ink-400 mb-2">Consent</p>
                <Badge tone={patient.consentGiven ? 'success' : 'danger'}>{patient.consentGiven ? 'Consent Given' : 'No Consent'}</Badge>
                <p className="text-xs text-ink-500 mt-1">Data shared: {patient.dataShared ? 'Yes' : 'No'}</p>
              </Card>
            </div>
          </div>
        )}

        {/* Consultations */}
        {activeTab === 'consultations' && (
          <div className="space-y-3">
            {patient.consultations.length === 0 && <p className="text-sm text-ink-500 text-center py-8">No consultations recorded.</p>}
            {patient.consultations.map((c) => (
              <Card key={c.id} padding="md">
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-sm font-bold text-ink-900">{c.diagnosis}</p>
                    <p className="text-xs text-ink-500 mt-0.5">{c.doctor} · {c.location}</p>
                    {c.notes && <p className="text-xs text-ink-600 mt-2">{c.notes}</p>}
                    {c.medications.length > 0 && (
                      <div className="mt-2 flex flex-wrap gap-1">
                        {c.medications.map((m) => <Badge key={m.id} tone="info" className="text-[10px]">{m.name}</Badge>)}
                      </div>
                    )}
                  </div>
                  <div className="text-right">
                    <p className="text-xs text-ink-500">{c.date}</p>
                    {c.followUpDate && <Badge tone="warning" className="mt-1 text-[10px]">Follow-up: {c.followUpDate}</Badge>}
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}

        {/* Prescriptions */}
        {activeTab === 'prescriptions' && (
          <div className="space-y-3">
            {patient.prescriptions.length === 0 && <p className="text-sm text-ink-500 text-center py-8">No prescriptions recorded.</p>}
            {patient.prescriptions.map((pr) => (
              <Card key={pr.id} padding="md">
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-sm font-bold text-ink-900">{pr.diagnosis}</p>
                    <p className="text-xs text-ink-500 mt-0.5">{pr.doctor} · {pr.issuedDate}</p>
                    <div className="mt-2 space-y-1">
                      {pr.medications.map((m) => (
                        <div key={m.id} className="flex items-center gap-2 text-xs">
                          <Badge tone="info" className="text-[10px] shrink-0">{m.name}</Badge>
                          <span className="text-ink-600">{m.dosage} · {m.frequency} · {m.duration}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                  <div className="text-right">
                    <Badge tone={pr.status === 'active' ? 'success' : pr.status === 'completed' ? 'info' : 'warning'}>{pr.status}</Badge>
                    <Button size="sm" variant="ghost" className="mt-2" onClick={() => handleDownloadPrescription(pr)} icon={<Download className="h-3 w-3" />}>Download</Button>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}

        {/* Lab Reports */}
        {activeTab === 'lab' && (
          <div className="space-y-3">
            {patient.labReports.length === 0 && <p className="text-sm text-ink-500 text-center py-8">No lab reports available.</p>}
            {patient.labReports.map((lr) => (
              <Card key={lr.id} padding="md">
                <div className="flex items-start justify-between">
                  <div>
                    <p className="text-sm font-bold text-ink-900">{lr.testName}</p>
                    <p className="text-xs text-ink-500 mt-0.5">{lr.testDate} · {lr.orderedBy}</p>
                    <p className="text-sm text-ink-700 mt-1">{lr.result}</p>
                    {lr.normalRange && <p className="text-xs text-ink-500 mt-0.5">Normal: {lr.normalRange}</p>}
                  </div>
                  <Badge tone={lr.flag === 'normal' ? 'success' : lr.flag === 'critical' ? 'danger' : 'warning'}>{lr.flag}</Badge>
                </div>
              </Card>
            ))}
          </div>
        )}

        {/* Allergies */}
        {activeTab === 'allergies' && (
          <div className="space-y-3">
            {patient.allergies.length === 0 && <p className="text-sm text-ink-500 text-center py-8">No known allergies.</p>}
            {patient.allergies.map((a) => (
              <Card key={a.id} padding="md" className="border-danger-200 bg-danger-50/30">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm font-bold text-ink-900">{a.substance}</p>
                    <p className="text-xs text-ink-500">Severity: {a.severity} · Reaction: {a.reaction}</p>
                  </div>
                  <Badge tone="danger">{a.severity}</Badge>
                </div>
              </Card>
            ))}
          </div>
        )}
      </div>
    </DashboardLayout>
  );
}
